### ISSUE TITLE
Fix compile error in build.gradle.kts on Gradle 7.6

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#686]
The build file (`build.gradle.kts`) does not compile on Gradle 7.6-rc-3:

```
  Line 300: implementation(project)
	^ None of the following functions can be called with the arguments supplied: 
	    public operator fun DependencyAdder.invoke(dependencyNotation: CharSequence): Unit defined in org.gradle.kotlin.dsl
	    public operator fun DependencyAdder.invoke(dependency: Dependency): Unit defined in org.gradle.kotlin.dsl
	    public operator fun DependencyAdder.invoke(files: FileCollection): Unit defined in org.gradle.kotlin.dsl
	    public operator fun DependencyAdder.invoke(dependency: Provider<out Dependency>): Unit defined in org.gradle.kotlin.dsl
	    public operator fun DependencyAdder.invoke(externalModule: ProviderConvertible<out MinimalExternalModuleDependency>): Unit defined in org.gradle.kotlin.dsl

1 error
```

See, e.g., [this build](https://github.com/junit-pioneer/junit-pioneer/actions/runs/3462615798/jobs/5781942468#step:6:97).

**Comment by melix** [comment]
You should be able to use `implementation(project(":junit-pioneer"))` instead (if `:junit-pioneer` is the path of the current project, if I got it correctly).

**Comment by carterkozak** [comment]
I've pushed #687 which provides more standard syntax (with the caveat that I don't have experience with Kotlin, but it's what I'd do in groovy!)

**Comment by jvandort** [comment]
While you cannot use `project` directly as a dependency, you can use the new syntax `implementation(project())`. The `project()` method is provided by [Dependencies](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/Dependencies.java#L55-L60), an interface which `JvmComponentDependencies` implements, and returns a `ProjectDependency` for your current project.

**Comment by nipafx** [comment]
Thank you @carterkozak! 🙏🏾 I just pulled `main` to apply your proposal [as given on Mastodon](https://mastodon.social/@carter_kozak/109343067748504287) and was surprised to already see it in action. Very cool!

@jvandort That looks like the cleaner syntax but it only works on Gradle 7.6, not on 7.5 yet and we need to build on both. (Because the "real" builds run with 7.5 and experimental ones with 7.6 to preview problems like these.) We can switch to the cleaner `project()` as soon as we rely on 7.6. 👍🏾

**Comment by xuan-nguyen-swe** [comment]
Using `project()` in gradle 7.6, I get error:

```
* Where:
Build file 'C:\Workspace\Projects\private\Homeschool\parent-tools\parent-tools-api\build.gradle.kts' line: 112

* What went wrong:
Script compilation error:

  Line 112:         implementation(project())
                                   ^ None of the following functions can be called with the arguments supplied: 
                                       public abstract fun project(p0: String!): Project! defined in org.gradle.api.Project
                                       public abstract fun project(p0: String!, p1: Closure<(raw) Any!>!): Project! defined in org.gradle.api.Project
                                       public abstract fun project(p0: String!, p1: Action<in Project!>!): Project! defined in org.gradle.api.Project
```
